name: misty.life

on:
  push:
    branches:
      master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: deploy
        if: github.ref == 'refs/heads/master'
        run: |
          mkdir -p ~/.ssh
          cat > ~/.ssh/id_ed25519 << EOF
          ${{ secrets.SSH_PRIVATE_KEY }}
          EOF
          chmod 0400 ~/.ssh/id_ed25519
          # ignore host fingerprint
          cat > ~/.ssh/config << EOF
          StrictHostKeyChecking no
          EOF
          rsync -avz public/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_DEST }}
